### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by vahidalvandi** [mmdsharifi/AdminLTE-RTL#3]
hi mr sharifi .
very thanks for adminlte-RTL

**Comment by mmdsharifi** [comment]
Hi , @webineh
I so happy for your feedback.
you're welcome.

**Comment by mmdsharifi** [comment]
Hi , @webineh
I so happy for your feedback.
you're welcome.

**Comment by mmdsharifi** [comment]
Hi , @webineh
I so happy for your feedback.
you're welcome.

**Comment by mohamedsharaf** [comment]
@mmdsharifi 
how can i use both versions 
ltr and rtl 

i opened css and there is rtl.css but it is empty

is there is a way to make it like this 

bootstrap-rtl
css\adminlte.css
css\adminlte-rtl.css
index.html
index-rtl.html

also when will u update to latest adminlte 

thanks for the great work

**Comment by mmdsharifi** [comment]
you can use **rtl css** plugin to convert LTR to RTL styles.
https://www.npmjs.com/package/grunt-rtlcss

and I update repo with this plugin ASAP.

**Comment by mohamedsharaf** [comment]
can u post your grunt rtl setting u used 

{
    preserveComments: true,
    preserveDirectives: false,
    swapLeftRightInUrl: true,
    swapLtrRtlInUrl: true,
    swapWestEastInUrl: true,
    autoRename: true,
    greedy: false,
    stringMap:[...],
    enableLogging: false,
    minify:false
}

**Comment by vahidalvandi** [comment]
how i use this command in grunt?

please tutorial step by step for use better 

thanks

**Comment by mmdsharifi** [comment]
for tutorials google it or ask in stackoverflow.
