### ISSUE TITLE
AdminLTE-RTL Laravel 5 

### ISSUE THREAD

**Issue by Dhiaa-M** [mmdsharifi/AdminLTE-RTL#7]
Salam
Could you put laravel 5 package for AdminLTE-RTL?
Thank you.

**Comment by mmdsharifi** [comment]
Hi,
You can use this repo https://github.com/acacha/adminlte-laravel .
 for RTLizition as mentioned in previous issues use rtlcss https://github.com/MohammadYounes/rtlcss .

With regards 
Mohammad Sharifi
