### ISSUE TITLE
footer is not fixed at bottom of page

### ISSUE THREAD

**Issue by moeinrahimi** [mmdsharifi/AdminLTE-RTL#8]
hi first of all i want to thank you for your amazing job, it is very helpful.
my issue is that when my content-wrapper class is empty the footer gets bigger

![screenshot 4](https://cloud.githubusercontent.com/assets/13715024/17392173/c6c5b35c-5a30-11e6-922f-4cd1ca30e54e.png)

the source code is avaliable here [https://almsaeedstudio.com/themes/AdminLTE/starter.html](admin panel)

**Comment by mmdsharifi** [comment]
Hi, 
Thanks for you'r opening issue, I recommend use flex box to solve it. At this moment I can put time to fix it, if you can, make pull request.

recommended solution:
- solved by flexbox :  https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/

 pull request

- fork this repository
- clone you'r repository
- fix issue via recommended solution on **branch** `fix-footer-issue` or any thing ...
- push you'r branch to this repo



Thanks you :+1:
